# Generated by Django 4.1.3 on 2022-12-01 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dispositivo",
            fields=[
                ("id_dispositivo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=20)),
                ("descripcion", models.CharField(max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[("0", "Apagado"), ("1", "Encendido")], max_length=1
                    ),
                ),
                ("valor", models.SmallIntegerField()),
                ("pin", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Hogar",
            fields=[
                ("id_hogar", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=30)),
                ("pin", models.SmallIntegerField()),
                ("lugar", models.CharField(max_length=30)),
                ("direccion", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                ("id_modulo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=30)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("A", "Actuador"), ("S", "Sensor")], max_length=1
                    ),
                ),
                (
                    "senal",
                    models.CharField(
                        choices=[("A", "Analoga"), ("D", "Digital"), ("P", "PWM")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("usuario", models.CharField(max_length=30)),
                ("contrasena", models.CharField(max_length=30)),
                ("correo", models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Informe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_antes", models.IntegerField()),
                ("valor_actual", models.IntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "id_dispositivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.dispositivo",
                    ),
                ),
                (
                    "id_hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.hogar"
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.usuario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="id_hogar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.hogar"
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="id_modulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.modulo"
            ),
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "id_hogar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.hogar"
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
                    ),
                ),
            ],
        ),
    ]
